# Generated by Django 5.1.1 on 2024-09-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Lesson link'),
        ),
    ]
